Repository 2025-DSWU-CS-FP/EYEDIA_BE, pull requests merged in 2025-05, with the labels that each got.

#6 ✨ Feat: 로그인/회원가입 기능 구현
  build.gradle
  src/main/java/com/eyedia/eyedia/config/AppConfig.java
  src/main/java/com/eyedia/eyedia/config/SecurityConfig.java
  src/main/java/com/eyedia/eyedia/controller/AuthController.java
  src/main/java/com/eyedia/eyedia/dto/UserLoginDTO.java
  src/main/java/com/eyedia/eyedia/dto/UserSignupDTO.java
  src/main/java/com/eyedia/eyedia/repository/UserRepository.java
  src/main/java/com/eyedia/eyedia/service/impl/AuthService.java
Labels: :sparkles: feature

#9 🐛 Bug: Swagger 연동 오류 수정
  build.gradle
Labels: :bug: bug

#11 ✨Feat: 스웨거 설정
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/eyedia/eyedia/.DS_Store
  src/main/java/com/eyedia/eyedia/config/SecurityConfig.java
  src/main/java/com/eyedia/eyedia/controller/AiToBackendController.java
  src/main/java/com/eyedia/eyedia/controller/UserFacingController.java
  src/main/java/com/eyedia/eyedia/domain/Message.java
  src/main/java/com/eyedia/eyedia/dto/AiToBackendDTO.java
  src/main/java/com/eyedia/eyedia/repository/MessageRepository.java
  src/main/java/com/eyedia/eyedia/service/MessageCommandService.java
  src/main/java/com/eyedia/eyedia/service/UserFacingService.java
Labels: :bug: bug, :sparkles: feature

#14 ✨Feat: chat with ai
  src/main/java/com/eyedia/eyedia/controller/AiToBackendController.java
  src/main/java/com/eyedia/eyedia/dto/AiToBackendDTO.java
  src/main/java/com/eyedia/eyedia/dto/ObjectDTO.java
  src/main/java/com/eyedia/eyedia/service/MessageCommandService.java
Labels: :sparkles: feature

#30 ✨ Feat: 채팅방 시작, 기록 가져오는 api 수정
  src/main/java/com/eyedia/eyedia/controller/UserFacingController.java
  src/main/java/com/eyedia/eyedia/domain/Painting.java
  src/main/java/com/eyedia/eyedia/dto/UserFacingDTO.java
  src/main/java/com/eyedia/eyedia/service/UserFacingService.java
Labels: :memo: docs, :sparkles: feature, :recycle: refactor
